#!/bin/bash

# pull submodules
cd "$HOME"
echo "Init submodules"
yadm submodule update --recursive --init

echo "Update submodules"
yadm pull --recurse-submodules

echo "Install oh-my-zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo "Installing vim plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall
