#!/bin/bash

# pull submodules
cd "$HOME"
echo "Init submodules"
yadm submodule update --recursive --init

echo "Update submodules"
yadm pull --recurse-submodules

echo "Installing vim plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall
